# version tag is obsolete and removed

services:
  # --- Standby Replication Service ---
  laterbase-standby:
    build:
      context: ./app # Updated context
      dockerfile: Dockerfile # Use the main Dockerfile (relative to context)
    container_name: laterbase_standby
    env_file:
      - .env
    environment:
      # --- Required by setup_standby.sh ---
      PRIMARY_HOST: ${PRIMARY_HOST}
      REPL_PASSWORD: ${REPL_PASSWORD}
      # --- PostgreSQL Runtime Configuration (sourced from .env, with defaults) ---
      # User that the PostgreSQL server runs as and owns the data directory
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      # Placeholder database name created on init (actual data comes from primary)
      POSTGRES_DB: ${POSTGRES_DB:-laterbase_standby_db}
      # Path inside the container where PostgreSQL data is stored
      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}
      # Required by base image entrypoint when initializing an empty PGDATA
      POSTGRES_PASSWORD: ${REPL_PASSWORD}

      # --- Other Settings ---
      POSTGRES_INITDB_ARGS: "--no-sync" # Faster init, safe for initial setup
    volumes:
      # Mount a persistent volume for the standby database data
      # The target path MUST match the PGDATA environment variable
      - laterbase_standby_data:${PGDATA:-/var/lib/postgresql/data/pgdata}
    ports:
      # Map standby's internal port 5432 to host port 5433
      - "5433:5432"
    restart: unless-stopped
    networks:
      - network

  # --- Hourly Backup Agent Service ---
  laterbase-backup-agent:
    build:
      context: ./backup # Updated context
      dockerfile: Dockerfile.backup # Use the backup Dockerfile (relative to context)
    container_name: laterbase_backup_agent
    env_file:
      - .env
    environment:
      # Required by backup.sh:
      PRIMARY_HOST: ${PRIMARY_HOST}
      PGPASSWORD: ${REPL_PASSWORD} # backup.sh expects PGPASSWORD
      PRIMARY_DB: ${PRIMARY_DB:-YOUR_RESOLVE_DB_NAME_HERE} # Add PRIMARY_DB to .env!
      PRIMARY_PORT: ${PRIMARY_PORT:-5432}
      PRIMARY_USER: ${PRIMARY_USER:-postgres}
      RCLONE_REMOTE_NAME: ${RCLONE_REMOTE_NAME:-} # e.g., mygdrive
      RCLONE_REMOTE_PATH: ${RCLONE_REMOTE_PATH:-} # e.g., resolve_backups
      BACKUP_RETENTION_DAYS: ${BACKUP_RETENTION_DAYS:-7} # Default 7 days
    volumes:
      # Mount a local directory on the host to store the backups
      - ./backups:/backups
      - ./rclone_config:/config # Allow writing for dynamic config
    restart: unless-stopped
    labels:
      ofelia.enabled: "true"
      # Schedule backup script execution
      ofelia.job-exec.laterbase-backup.schedule: "@hourly" # Or use cron format e.g., "0 * * * *"
      ofelia.job-exec.laterbase-backup.container: "laterbase_backup_agent"
      ofelia.job-exec.laterbase-backup.command: "/app/backup.sh"
      # Schedule entrypoint script execution on startup for dynamic config
      ofelia.job-exec.laterbase-config.schedule: "@reboot"
      ofelia.job-exec.laterbase-config.container: "laterbase_backup_agent"
      ofelia.job-exec.laterbase-config.command: "/usr/local/bin/entrypoint.sh"
    networks:
      - network

  # --- pgAdmin UI Service ---
  laterbase-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: laterbase_pgadmin
    environment:
      # Set these in your .env file or replace placeholders here
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-YOUR_PGADMIN_EMAIL_HERE}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-YOUR_PGADMIN_PASSWORD_HERE}
      PGADMIN_LISTEN_PORT: 80
    ports:
      # Map host port 5050 to pgAdmin container port 80
      - "5050:80"
    volumes:
      # Persist pgAdmin configuration and server definitions
      # Persist pgAdmin configuration and server definitions using a named volume
      - laterbase_pgadmin_data:/var/lib/pgadmin
    networks:
      - network
    restart: unless-stopped

  # --- Ofelia Scheduler Service ---
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: laterbase_scheduler
    depends_on:
      - laterbase-backup-agent # Ensure backup agent container exists
    command: daemon --docker
    volumes:
      # Mount docker socket to allow Ofelia to interact with Docker daemon
      - /var/run/docker.sock:/var/run/docker.sock:ro # Read-only is safer
    networks:
      - network
    restart: unless-stopped

volumes:
  # Volume for standby PostgreSQL data
  laterbase_standby_data:
    driver: local
  # Volume for pgAdmin data
  laterbase_pgadmin_data:
    driver: local

networks:
  # Network for communication between services
  network:
    driver: bridge