name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write # Needed to push images to GHCR

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push app image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/laterbase-app:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/laterbase-app:latest

      - name: Build and push backup image
        uses: docker/build-push-action@v5
        with:
          context: ./backup
          file: ./backup/Dockerfile.backup # Using the specific name
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/laterbase-backup:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/laterbase-backup:latest

      - name: Build and push restore_ui image
        uses: docker/build-push-action@v5
        with:
          context: ./restore_ui
          file: ./restore_ui/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/laterbase-restore-ui:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/laterbase-restore-ui:latest